site:
  title: Jmix Documentation
  start_page: jmix:ROOT:intro.adoc
  url: https://docs.jmix.io/
content:
  sources: 
  - url: https://github.com/jmix-framework/jmix-docs.git
    branches:
    - release_2_3
    - release_2_2
    - release_2_1
    - release_2_0
    start_path: content
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./content/supplemental
asciidoc:
  extensions:
    - asciidoctor-kroki
antora:
  extensions:
    - require: '@jmix-framework/lunr-extension'
      index_latest_only: true
